Repository redhat-appstudio/tssc-test, pull requests merged in 2025-10, with the labels that each got.

#169 [azure-set-var-fix] Change default Azure pool name and var group to regexes
  src/rhtap/modification/contentModification.ts
  src/rhtap/postcreation/strategies/commands/modifyAzureFiles.ts
Labels: bug-fix

#168 [RHTAP-5632] Unify file naming under ui/
  README.md
  src/ui/commonUi.ts
  src/ui/page-objects/dependenciesPo.ts
  src/ui/plugins/argocd.ts
  src/ui/plugins/dependencies/dependenciesUiPlugin.ts
  src/ui/plugins/docs/docsUiPlugin.ts
  src/ui/plugins/git/gitUiFactory.ts
  src/ui/plugins/git/githubUi.ts
  src/ui/plugins/git/gitlabUi.ts
  tests/setup/auth.setup.ts
  tests/ui/component.test.ts
  tests/ui/gitopsResource.test.ts
Labels: enhancement, testing, ui-testing

#129 tests(ui): add CI provider test for Pipeline Runs
  src/ui/page-objects/tektonPo.ts
  src/ui/plugins/ci/baseCIPlugin.ts
  src/ui/plugins/ci/ciPlugin.ts
  src/ui/plugins/ci/tektonPlugin.ts
  tests/ui/component.test.ts
Labels: enhancement, testing, ui-testing

#170 [RHTAP-5676] Verify Gitlab
  src/ui/plugins/git/gitUi.ts
  src/ui/plugins/git/gitUiFactory.ts
  src/ui/plugins/git/gitUiInterface.ts
  src/ui/plugins/git/githubUi.ts
  src/ui/plugins/git/gitlabUi.ts
  tests/ui/component.test.ts
Labels: documentation, enhancement, testing, ui-testing

#174 RHTAP-5691 Test plan filtering
  README.md
  integration-tests/config/testplan.json
  playwright.config.ts
  scripts/generateProjectConfig.ts
  src/playwright/testplan.ts
  src/utils/testFilterLoader.ts
  templates/testplan.json
Labels: enhancement, configuration, testing
