Repository redhat-appstudio/tssc-test, pull requests merged in 2025-09, with the labels that each got.

#133 [ci-test-fix] Excludes githubactions from UI tests
  tests/ui/ui.test.ts
Labels: testing, ui-testing

#152 Remove bitbucket as git provider
  integration-tests/config/testplan.json
Labels: configuration, testing

#148 [RHTAPUI-53] Adds tests for Tekton CI provider
  playwright.config.ts
  src/ui/page-objects/acsPo.ts
  src/ui/page-objects/ciPo.ts
  src/ui/page-objects/commonPo.ts
  src/ui/page-objects/loginPo.ts
  src/ui/page-objects/tektonPo.ts
  src/ui/plugins/ci/baseCIPlugin.ts
  src/ui/plugins/ci/ciFactory.ts
  src/ui/plugins/ci/ciPlugin.ts
  src/ui/plugins/ci/tektonPlugin.ts
  src/ui/plugins/git/github.ts
  src/ui/uiComponent.ts
  src/utils/util.ts
  tests/ui/component.test.ts
Labels: enhancement, testing, integration, ui-testing

#156 RHTAP-5665 Fix getting azure pipelineRun Logs
  integration-tests/config/testplan.json
  src/api/ci/azureClient.ts
  src/rhtap/core/integration/ci/providers/azureCI.ts
  src/rhtap/postcreation/strategies/commands/addAzureSecrets.ts
Labels: configuration, testing, api-client, integration, bug-fix, security
