Repository redhat-appstudio/tssc-test, pull requests merged in 2025-08, with the labels that each got.

#91 Add CodeRabbit configuration for TSSC E2E Testing Framework
  .coderabbit.yaml
Labels: configuration

#95 Increase maxRetries from 50 seconds to 120 for component creation in RHDH
  src/api/rhdh/developerhub.ts
Labels: api-client, bug-fix

#104 Enhance ArgoCD sync command execution with retry logic.
  src/api/argocd/services/sync.service.ts
Labels: enhancement, api-client, bug-fix

#105 Remove GitLab CI and Bitbucket from suite
  integration-tests/config/testplan.json
Labels: configuration, testing

#107 Increase default timeout in GithubActionsService to 155 seconds.
  src/api/github/services/github-actions.service.ts
Labels: api-client, bug-fix

#97 Add 4.19 to rhads-config
  integration-tests/config/rhads-config
Labels: configuration, testing

#128 [coderabbit-config] Switches coderabbit profile to chill
  .coderabbit.yaml
Labels: configuration
